### ISSUE TITLE
тормозит загрузку браузера

### ISSUE THREAD

**Issue by elvin-nsk** [Noperkot/TorrServerAdder#10]
Браузер Vivaldi, портативная установка. Система Windows 11.

При первом запуске браузера после перезагрузки системы браузер зависает на 10-20 секунд, ни на что не реагирует.

Отключил плагины - нормально. Включал по одному, перезагружался каждый раз. Зависания начались на TorrServerAdder. Отключил его, включил остальные - всё нормально. Так что, наверное, дело в нём.

**Comment by Noperkot** [comment]
Погонял на Win10, в том числе с перезагрузками перед запуском, [проблема не проявилась](https://youtu.be/UtP9ENWC2ZA)
Vivaldi 5.7.2921.65 (Stable channel) (64 бита),  portable installation
ОС Windows 10 Version 1607 (Build 14393)
TorrServer Adder 2.0.1

Попробуйте 
- удалить/установить расширение
- на время отключить антивирус/другие блокировщики
- другую портативную установку браузера Vivaldi
- другой браузер, например [Cent Browser](https://www.centbrowser.com)

Возможно это шалит win11, у меня ее нет.

**Comment by elvin-nsk** [comment]
Посмотрел ваше видео и догадался сделать то, что надо было сделать с самого начала: попробовал на отдельной портативной установке. Всё работает.

Спасибо, что уделили время, и спасибо за расширение, полезное :)
