### ISSUE TITLE
Try implement "show categories" option

### ISSUE THREAD

**Issue by filimonic** [Noperkot/TorrServerAdder#16]
TS now supports [categories](https://github.com/YouROK/TorrServer/blob/master/web/src/components/categories.jsx) as an option while uploading files. 
Please if you implement it, make it "disable-able" to keep TSAdder as simple as possible.

**Comment by Noperkot** [comment]
Currently, the extension's work has nothing to do with categories. What should this "disable-able" look like in an extension?

**Comment by filimonic** [comment]
Just asking if you ever implement ability to choose category in context menu, please make this ability "disableable" to keep right button menu simple.14 апр. 2024 г. 08:14 пользователь Noperkot ***@***.***> написал:
Currently, the extension's work has nothing to do with categories. What should this "disable-able" look like in an extension?

**Comment by Noperkot** [comment]
I plan to add the category to profile. This will not affect the context menu in any way.

![Снимок](https://github.com/Noperkot/TorrServerAdder/assets/92878142/02f09584-fcb0-41a4-a69c-efe798ebebbd)
